### PR TITLE
CORE-1875: accessible resource query generation

### PR DESCRIPTION
**Pull request by slr71**

### CODE REVIEW

**Review by ianmcorvidae — APPROVED** [review]
This seems good to me. The one thought I'd have is that the name of the permissions schema should possibly be configurable. When I was migrating DBs to schemas I was usually trying to add helper functions that generated the names so the schema could, in theory, be whatever we wanted.

Here's the one that I'd used in a clojure project:

```clojure
(defn t
  [tname]
  (keyword (db-schema) tname))
```

(where `(db-schema)` is calling into the configuration for the service, in this case).

Take that or leave it, I figure, but a possible small improvement.

**Comment by slr71** [comment]
That sounds like a good idea; I'll add an option for that.

**Review by psarando — APPROVED** [review]
LGTM 👍

**Comment by slr71** [comment]
Thanks for the reviews!

**Pull request merged**
